
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                0
#define PARTNER_STEVEN              1
#define PARTNER_RAYQUAZA            2

#define PARTNER_MAY_MUDKIP_METEOR_FALLS 3
#define PARTNER_MAY_TORCHIC_METEOR_FALLS 4
#define PARTNER_MAY_TREECKO_METEOR_FALLS 5
#define PARTNER_BRENDAN_MUDKIP_METEOR_FALLS 6
#define PARTNER_BRENDAN_TORCHIC_METEOR_FALLS 7
#define PARTNER_BRENDAN_TREECKO_METEOR_FALLS 8
#define PARTNER_MAY_VICTORY_ROAD_TORCHIC 9
#define PARTNER_MAY_VICTORY_ROAD_MUDKIP 10
#define PARTNER_MAY_VICTORY_ROAD_TREECKO 11
#define PARTNER_BRENDAN_VICTORY_ROAD_TORCHIC 12
#define PARTNER_BRENDAN_VICTORY_ROAD_MUDKIP 13
#define PARTNER_BRENDAN_VICTORY_ROAD_TREECKO 14

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
