
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                0
#define PARTNER_STEVEN              1
#define PARTNER_RAYQUAZA            2

#define PARTNER_RIVAL_RUSTBORO 3
#define PARTNER_MAY_RUSTBORO_MUDKIP (PARTNER_RIVAL_RUSTBORO)
#define PARTNER_MAY_RUSTBORO_TORCHIC (PARTNER_RIVAL_RUSTBORO + 1)
#define PARTNER_MAY_RUSTBORO_TREECKO (PARTNER_RIVAL_RUSTBORO + 2)
#define PARTNER_BRENDAN_RUSTBORO_MUDKIP (PARTNER_RIVAL_RUSTBORO + 3)
#define PARTNER_BRENDAN_RUSTBORO_TORCHIC (PARTNER_RIVAL_RUSTBORO + 4)
#define PARTNER_BRENDAN_RUSTBORO_TREECKO (PARTNER_RIVAL_RUSTBORO + 5)

#define PARTNER_RIVAL_ROUTE_110 (PARTNER_BRENDAN_RUSTBORO_TREECKO + 1)
#define PARTNER_MAY_ROUTE_110_MUDKIP (PARTNER_RIVAL_ROUTE_110)
#define PARTNER_MAY_ROUTE_110_TORCHIC (PARTNER_RIVAL_ROUTE_110 + 1)
#define PARTNER_MAY_ROUTE_110_TREECKO (PARTNER_RIVAL_ROUTE_110 + 2)
#define PARTNER_BRENDAN_ROUTE_110_MUDKIP (PARTNER_RIVAL_ROUTE_110 + 3)
#define PARTNER_BRENDAN_ROUTE_110_TORCHIC (PARTNER_RIVAL_ROUTE_110 + 4)
#define PARTNER_BRENDAN_ROUTE_110_TREECKO (PARTNER_RIVAL_ROUTE_110 + 5)

#define PARTNER_RIVAL_METEOR_FALLS (PARTNER_BRENDAN_ROUTE_110_TREECKO + 1)
#define PARTNER_MAY_MUDKIP_METEOR_FALLS (PARTNER_RIVAL_METEOR_FALLS)
#define PARTNER_MAY_TORCHIC_METEOR_FALLS (PARTNER_RIVAL_METEOR_FALLS + 1)
#define PARTNER_MAY_TREECKO_METEOR_FALLS (PARTNER_RIVAL_METEOR_FALLS + 2)
#define PARTNER_BRENDAN_MUDKIP_METEOR_FALLS (PARTNER_RIVAL_METEOR_FALLS + 3)
#define PARTNER_BRENDAN_TORCHIC_METEOR_FALLS (PARTNER_RIVAL_METEOR_FALLS + 4)
#define PARTNER_BRENDAN_TREECKO_METEOR_FALLS (PARTNER_RIVAL_METEOR_FALLS + 5)

#define PARTNER_RIVAL_ROUTE_119 (PARTNER_BRENDAN_TREECKO_METEOR_FALLS + 1)
#define PARTNER_MAY_ROUTE_119_MUDKIP (PARTNER_RIVAL_ROUTE_119)
#define PARTNER_MAY_ROUTE_119_TORCHIC (PARTNER_RIVAL_ROUTE_119 + 1)
#define PARTNER_MAY_ROUTE_119_TREECKO (PARTNER_RIVAL_ROUTE_119 + 2)
#define PARTNER_BRENDAN_ROUTE_119_MUDKIP (PARTNER_RIVAL_ROUTE_119 + 3)
#define PARTNER_BRENDAN_ROUTE_119_TORCHIC (PARTNER_RIVAL_ROUTE_119 + 4)
#define PARTNER_BRENDAN_ROUTE_119_TREECKO (PARTNER_RIVAL_ROUTE_119 + 5)

#define PARTNER_RIVAL_LILYCOVE (PARTNER_BRENDAN_ROUTE_119_TREECKO + 1)
#define PARTNER_MAY_LILYCOVE_MUDKIP (PARTNER_RIVAL_LILYCOVE)
#define PARTNER_MAY_LILYCOVE_TORCHIC (PARTNER_RIVAL_LILYCOVE + 1)
#define PARTNER_MAY_LILYCOVE_TREECKO (PARTNER_RIVAL_LILYCOVE + 2)
#define PARTNER_BRENDAN_LILYCOVE_MUDKIP (PARTNER_RIVAL_LILYCOVE + 3)
#define PARTNER_BRENDAN_LILYCOVE_TORCHIC (PARTNER_RIVAL_LILYCOVE + 4)
#define PARTNER_BRENDAN_LILYCOVE_TREECKO (PARTNER_RIVAL_LILYCOVE + 5)

#define PARTNER_RIVAL_VICTORY_ROAD (PARTNER_BRENDAN_LILYCOVE_TREECKO + 1)
#define PARTNER_MAY_VICTORY_ROAD_TORCHIC (PARTNER_RIVAL_VICTORY_ROAD)
#define PARTNER_MAY_VICTORY_ROAD_MUDKIP (PARTNER_RIVAL_VICTORY_ROAD + 1)
#define PARTNER_MAY_VICTORY_ROAD_TREECKO (PARTNER_RIVAL_VICTORY_ROAD + 2)
#define PARTNER_BRENDAN_VICTORY_ROAD_TORCHIC (PARTNER_RIVAL_VICTORY_ROAD + 3)
#define PARTNER_BRENDAN_VICTORY_ROAD_MUDKIP (PARTNER_RIVAL_VICTORY_ROAD + 4)
#define PARTNER_BRENDAN_VICTORY_ROAD_TREECKO (PARTNER_RIVAL_VICTORY_ROAD + 5)

#define PARTNER_RED (PARTNER_BRENDAN_VICTORY_ROAD_TREECKO + 1)
#define PARTNER_RED_PETALBURG_WOODS (PARTNER_RED)
#define PARTNER_RED_FALLARBOR (PARTNER_RED + 1)
#define PARTNER_RED_ROUTE121 (PARTNER_RED + 2)
#define PARTNER_RED_VICTORY_ROAD (PARTNER_RED + 3)

#define PARTNER_WALLY (PARTNER_RED_VICTORY_ROAD + 1)
#define PARTNER_WALLY_PETALBURG (PARTNER_WALLY)
#define PARTNER_WALLY_MAUVILLE (PARTNER_WALLY + 1)
#define PARTNER_WALLY_VICTORY_ROAD (PARTNER_WALLY + 2)

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
